FROM bobpace/devbox-dotfiles
MAINTAINER Bob Pace <bob.pace@gmail.com>

RUN sudo apt-get install -y --no-install-recommends nodejs npm && \
    sudo ln -s /usr/bin/nodejs /usr/bin/node

CMD ["/bin/bash"]
